- name: Wails Build Action
  # You may pin to the exact commit or the version.
  # uses: dAppServer/wails-build-action@ea084a9005380833a7ae035ad0ba046e03073273
  uses: dAppServer/wails-build-action@v1
  with:
    # Platform to build for
    build-platform: # optional, default is darwin/universal
    # Wails version to use
    wails-version: # optional, default is latest
    # Webview2 installer method [download,embed,browser,error]
    wails-build-webview2: # optional, default is download
    # Version of Go to use
    go-version: # optional, default is 1.17
    # Node js version
    node-version: # optional, default is 16.x
    # This gets run into bash, use the full command
    deno-build: # optional, default is 
    # This gets run into bash, use the full command
    deno-working-directory: # optional, default is .
    # Deno version to use
    deno-version: # optional, default is v1.20.x
